### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'key'

### ISSUE THREAD

**Issue by icvplayer** [EchoDreamer/Q-KGR#1]
When I try to run "script/obqa_t5_lora.sh", the program begin to report an error: TypeError: forward() got an unexpected keyword argument 'key', it seems like that the "forward" method from "T5Block" can not accept the parameter "key", so how to solve it?

**Comment by EchoDreamer** [comment]
Do you download and install the transformers (https://huggingface.co/271754echo/Q-KGR/)? The modified version has added the argument 'key' in the forward method of the T5Block

**Comment by icvplayer** [comment]
Thanks, I am sorry I didn't install this library.
